"""Keep runtime console output in English, including third-party callbacks.

The source record is kept intact. This only affects human-facing stdout and
stderr from the live process, where a model failure can otherwise print a
Chinese fallback as if it were a generated answer.
"""
from __future__ import annotations

import re
import sys


_PHRASES = (
    ("运行失败", "Run failed"),
    ("运行完成", "Run completed"),
    ("推演已结束", "Simulation finished"),
    ("服务已关闭", "Service closed"),
    ("本次运行", "This run"),
    ("成品记录", "final record"),
    ("正在映射", "Mapping"),
    ("映射失败", "Mapping failed"),
    ("已生成", "generated"),
    ("已保存", "saved"),
    ("界面已启动", "Interface started"),
    ("小镇", "town"),
    ("结果记录", "results and records"),
    ("仅审阅模式", "Review mode"),
    ("没有在推演", "No simulation is running"),
    ("重开请求", "restart request"),
    ("已中断", "Interrupted"),
    ("连接出错", "Connection error"),
    ("全部尝试失败", "All attempts failed"),
    ("返回兜底值", "returning fallback value"),
    ("不是模型说的", "not generated by the model"),
    ("调用失败", "request failed"),
    ("输出被", "Output was"),
    ("截断", "truncated"),
    ("端点拒绝", "Endpoint rejected"),
    ("初始坐标取不到", "Initial coordinates unavailable"),
    ("无解", "no path"),
    ("停在原地", "staying in place"),
)
_HAN = re.compile(r"[\u3400-\u9fff]+")


def english_output(value: str) -> str:
    """Translate known status text; label remaining legacy text explicitly."""
    result = str(value)
    for source, target in _PHRASES:
        result = result.replace(source, target)
    return _HAN.sub("[untranslated legacy detail]", result)


class EnglishStream:
    def __init__(self, stream):
        self.stream = stream

    def write(self, value):
        return self.stream.write(english_output(value))

    def flush(self):
        return self.stream.flush()

    def isatty(self):
        return self.stream.isatty()

    def fileno(self):
        return self.stream.fileno()

    def __getattr__(self, name):
        return getattr(self.stream, name)


def install_english_output():
    if not isinstance(sys.stdout, EnglishStream):
        sys.stdout = EnglishStream(sys.stdout)
    if not isinstance(sys.stderr, EnglishStream):
        sys.stderr = EnglishStream(sys.stderr)
